---
development:
   API_HOST: http://localhost:9090
   API_HOST: https://eventix-api.herokuapp.com
   API_VERSION: /api/v1


test:
  API_HOST: http://localhost:9090

production:
  API_HOST: https://eventix-api.herokuapp.com