
---
# Name your file secrets.yml

GH_TOKEN: <personal access token for github api>
PHQ_TOKEN: <personal access token for github api>
PHQ_CLIENT_ID: <personal access token for github api>
PHQ_SECRET_KEY: <personal access token for github api>